apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # The external port
      targetPort: 5000  # The internal port the Flask app is listening on
  type: ClusterIP
