apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # The port exposed by the service inside the cluster
      targetPort: 5000 # The port on the container where Flask is running
      nodePort: 30001  # The external port on the Kubernetes node (your local machine)
  type: NodePort      # Exposes the service outside of the cluster
