apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # Port accessible from outside the cluster
      targetPort: 5000  # The internal port on which Flask is running
