apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Match with the Flask app port inside the container
  type: ClusterIP  # You can change this to LoadBalancer if you want external access
